### ISSUE TITLE
Update deprecated GitHub actions 

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#535]
Update deprecated GitHub actions:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-dotnet@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by SilentSobs** [comment]
Hello, I'm interested in contributing to this issue.

I have a question about the default Node.js version used in GitHub Actions workflows. If we don't explicitly mention a Node.js version in the workflow YAML file, does it default to Node.js version 16?

I'm seeking confirmation on the following assumptions:

1. Checkout repository:
   The `actions/checkout@v3` action fetches your code.

2. Setup Node.js (default):
   The `actions/setup-node@v3` action runs, installing the default Node.js version (16) on the runner.

To explicitly specify a different Node version (e.g., version 20), is the following YAML configuration correct?
```
steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Setup Node.js 20
  uses: actions/setup-node@v3
  with:
    node-version: 20

- name: Setup .NET
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 8.0.x

```
So How can i identify the root yaml file ?

**Comment by waldekmastykarz** [comment]
If I'm not mistaken, the action's author decides which version of Node to use. So to fix this issue, we basically need to upgrade to the latest version of the actions that we use and see if everything works as intended (ie. there are no breaking changes between the version we use right now vs. the version we're updating to. If there are breaking changes, update the workflow to address them).

**Comment by SilentSobs** [comment]
I've made updates to our GitHub Actions workflow based on your suggestions. Here's the current draft:

 
 ```
name: 'Setup .NET Core SDK'

on:
  push:
    branches:
      - nodejs-setup

description: '.NET SDK'

inputs:
  dotnet-version: '8.0.x'

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run setup script
        run: node dist/setup/index.js
```
I'm particularly unsure about the line:
```
- name: Run setup script
  run: node dist/setup/index.js
```
Could you please confirm if I'm on the right track with this line, or if you have any recommendations?
